import Mathlib

#check FirstOrder.Field.isAlgClosed_of_model_ACF
#check FirstOrder.Field.modelField_of_modelACF
#check FirstOrder.Field.ACF_zero_realize_iff_infinite_ACF_prime_realize
#check IntermediateField.eq_bot_of_isAlgClosed_of_isAlgebraic
#check NumberField.InfinitePlace.comap_mk
#check NumberField.InfinitePlace.comap_id
